# Introduction to Data Science 2021

# Week 1

## Exercise 1 | Matrix warm-up
<span style="background-color: #ccfff2"> *Note: You can find tutorials for NumPy and Pandas under 'Useful tutorials' in Moodle.*</span>

One of the most useful properties of any scientific programming language (Python with NumPy, R, Julia, etc) is that they allow us to work with matrices efficiently. Let's learn more about these features!

### 1.1 Basics

1. Let's start by creating two arrays <span style="background-color: #ccfff2"> A</span> and <span style="background-color: #ccfff2"> B</span> which each have the integers <span style="background-color: #ccfff2"> 0, 1, 2, ..., 1e7-1</span>. Use the normal arrays or lists of the programming language you are using, e.g. *list* or *[ ]* in Python.

In [2]:
A = B = [i for i in range(0,int(1e7-1))]

2. Create a function that uses a <span style="background-color: #ccfff2"> for loop</span> or equivalent to return a new array <span style="background-color: #ccfff2"> C</span>, which contains the <span style="background-color: #ccfff2"> element-wise sum of *A* and *B*</span>, e.g. C should contain the integers <span style="background-color: #ccfff2"> 0, 2, 4, etc</span>.

In [3]:
def add_with_for(A,B):
    C = []
    for i in range(len(A)):
        C.append(A[i]+B[i])
    return C

add_with_for(A,B)

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

3. Next, let's create another function that uses NumPy (or equivalent) to do the same. To try it out, allocate two arrays (e.g. using <span style="background-color: #ccfff2"> np.array</span> in NumPy) and add the arrays together using your function. Don't use loops, instead, find out how to add the two arrays directly. What do you notice in comparison to the previous function?

In [4]:
import numpy as np
np_A = np_B = np.arange(0, int(1e7-1))
def add_with_np(A,B):
    C = np.add(A,B)
    return C

add_with_np(np_A,np_B)

# I can notice that it's really faster (1.6s using the for vs 0.1 using numpy on my machine)

array([       0,        2,        4, ..., 19999992, 19999994, 19999996])

### 1.2 Array manipulation

<span style="background-color: #ccfff2"> *Note: for the following exercises, only use NumPy or equivalent functions. Don't use any loops.* </span>
1. Create the following array:

*[hint: <span style="background-color: #ccfff2"> np.reshape</span>]*

In [5]:
# array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
#        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
#        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
#        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
#        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
#        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
#        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [6]:
np.reshape(np.arange(0,100),(10,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

2. Create the following array:

In [7]:
# array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [8]:
np.resize([0.,1.], (10,10))

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

3. Create the following array (D):

In [9]:
# array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [10]:
D = np.ones((10,10), float)
np.fill_diagonal(D, 0.)

4. Create the following array (E):

In [11]:
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
E = np.fliplr(D)

5. Call the last two matrices <span style="background-color: #ccfff2">D</span> and <span style="background-color: #ccfff2">E</span>, respectively. Show that the determinant of their product (matrix multiplication) is the same as the product of their determinants. That is calculate both <span style="background-color: #ccfff2">det(DE)</span> and <span style="background-color: #ccfff2">det(D) * det(E)</span>, and show that they are the same. Why does this hold in this instance? Does it hold in general? The product of the determinants (or the determinant of the product) should be -81.

In [13]:
f_det = int(np.linalg.det(np.matmul(D,E)))
s_det = int(np.linalg.det(D)*np.linalg.det(E))
print(f_det == s_det)

True


This holds in this instance for the Binet Theorem. In fact, the Binet Theorem states that:

Let ```A``` and ```B``` be two **square matrices** (i.e. with the number of columns equal to the number of rows), **with the same number of rows**, then the determinant of the product between A and B is equal to the product of the determinant of A and the determinant of B.

In this case the hypotesis is true, since both are square matrices and they have the same number of rows (two 10x10 matrices), so that applies.

### 1.3 Slicing

Array slicing is a powerful way to extract data from an array. Let's practice array slicing with the following exercises!

1. Load the [Boston housing dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_boston.html). The data should be a matrix of shape <span style="background-color: #ccfff2">(506, 13)</span>, that is 506 rows and 13 columns. Use the <span style="background-color: #ccfff2">.shape</span> attribute of NumPy arrays to verify this. Here's a [description of the fields](https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.names).

In [14]:
import sklearn
from sklearn import datasets
import pandas as pd
boston = sklearn.datasets.load_boston()
print(boston.data.shape)

(506, 13)


2. Select rows where the Crime feature <span style="background-color: #ccfff2">(CRIM)</span> is higher than 1. The first few row numbers should be <span style="background-color: #ccfff2">16, 20, 22</span> (zero-indexed). How many are there? *[hint: <span style="background-color: #ccfff2">np.where</span>]*

In [15]:
idx, = np.where(boston.feature_names == 'CRIM')[0]
rows = np.where(boston.data[:,idx]>1)
crim_higher_1 = boston.data[rows]
print(len(rows[0])) # 174

174


3. Select the rows where the pupil-to-teach ratio <span style="background-color: #ccfff2">(PTRATIO)</span> is between 16% and 18% (exclusive). There should be **100** of these.

In [16]:
idx, = np.where(boston.feature_names == 'PTRATIO')[0]
rows = np.where((boston.data[:,idx]>16) & (boston.data[:,idx]<18))
ptratio_between = boston.data[rows]
print(len(rows[0]))

100


4. Find the mean nitric oxides concentration <span style="background-color: #ccfff2">(NOX)</span> for homes whose median price is more than 25000 USD (the target variable). It should be around **0.492**.

In [17]:
idx, = np.where(boston.feature_names == 'NOX')[0]
rows = np.where(boston.target>25)
noxes = boston.data[rows]
print(np.mean(noxes[:,idx]))

0.4921201612903226


## Exercise 2 | Working with text data

Next, let's look into some text data. We will be looking into Amazon reviews, and the steps needed to transform a raw dataset into a format more suitable for prediction tasks.

1. Download the automotive 5-core dataset from [here](http://jmcauley.ucsd.edu/data/amazon/). Next, you can extract the data in <span style="background-color: #ccfff2">JSON</span> format. You can also download one of the bigger ones, if you are feeling ambitious. Open the JSON file. Access the <span style="background-color: #ccfff2">reviewText</span> field, which contains the unstructured review text written by the user. 

For instance the first review reads as follows: 

*'I needed a set of jumper cables for my new car and these had good reviews and were at a good price.  They have been used a few times already and do what they are supposed to - no complaints there.What I will say is that 12 feet really isn't an ideal length.  Sure, if you pull up front bumper to front bumper they are plenty long, but a lot of times you will be beside another car or can't get really close.  Because of this, I would recommend something a little longer than 12'.Great brand - get 16' version though.'*

In [21]:
import json
import pandas as pd
import numpy as np

automotive = pd.read_json(r'./Automotive_5.json', lines=True)

reviewTexts = automotive['reviewText']

2. Next, let's follow some steps to normalize the text data.

When dealing with natural language, it is important to notice that while, for example, the words "Copper" and "copper" are represented by two different strings, they have the same meaning. When applying statistical methods on this data, it is useful to ensure that words with the same meaning are represented by the same string.

* <span style="background-color: #ccfff2">Downcasing</span>: Let's first downcase the contents of the <span style="background-color: #ccfff2">reviewText</span> field.

Now the first review should be:

*'i needed a set of jumper cables for my new car and these had good reviews and were at a good price.  they have been used a few times already and do what they are supposed to - no complaints there.what i will say is that 12 feet really isn't an ideal length.  sure, if you pull up front bumper to front bumper they are plenty long, but a lot of times you will be beside another car or can't get really close.  because of this, i would recommend something a little longer than 12'.great brand - get 16' version though.'*

In [22]:
automotive['reviewText'] = automotive['reviewText'].str.lower()
#print(automotive['reviewText'].head(3))

0    i needed a set of jumper cables for my new car...
1    these long cables work fine for my truck, but ...
2    can't comment much on these since they have no...
Name: reviewText, dtype: object


3. Let's continue with punctuation and stop word removal. Stop words are words like "and", "the", etc. They are usually very common words that have little to do with the actual content matter. There's plenty openly available lists of stop words for almost any (natural) language.

* <span style="background-color: #ccfff2">Punctuation and stop-word removal</span>: Let's now remove all punctuation, as well as the stop words. You can find a stop word list for English, e.g. [here](http://xpo6.com/download-stop-word-list/) *(use the link for CSV download of english stop words)*.

First review at this point reads as: 

*'needed set jumper cables new car good reviews good price used few times already supposed complaints therewhat 12 feet really isnt ideal length sure pull up front bumper front bumper plenty long lot times beside another car cant really close recommend something little longer 12great brand 16 version though'*

In [24]:
# Remove puntuaction
import string
automotive['reviewText'] = automotive['reviewText'].str.replace('[{}]'.format(string.punctuation), '',regex=True)

# Remove stopwords
stopWords = pd.read_csv('./stop-word-list.csv', delimiter=', ', header=None, index_col=False, engine='python').to_numpy()[0]
automotive['reviewText'] = automotive['reviewText'].apply(lambda x: ' '.join([k for k in x.split() if k not in stopWords]))

#print(automotive['reviewText'].head(3))

0    needed set jumper cables new car good reviews ...
1    long cables work fine truck quality seems litt...
2    cant comment much used come back update review...
Name: reviewText, dtype: object


4. Let's continue with stemming. For example, while the words "swims" and "swim" are different strings, they both refer to swimming. [Stemming](https://en.wikipedia.org/wiki/Stemming) refers to the process of mapping words in inflected form to their base form, for instance: swims -> swim.

* <span style="background-color: #ccfff2">Stemming</span>: Apply a stemmer on the paragraphs, so that inflected forms are mapped to the base form. For example, for Python the popular natural language toolkit [nltk](http://www.nltk.org/howto/stem.html) has an easy to use stemmer. In case you are using R, you can try the [Snowball stemmer](https://www.rdocumentation.org/packages/corpus/versions/0.10.2/topics/stem_snowball).

Finally, after stemming: 

*'need set jumper cabl new car good review good price use few time alreadi suppos complaint therewhat 12 feet realli isnt ideal length sure pull up front bumper front bumper plenti long lot time besid anoth car cant realli close recommend someth littl longer 12great brand 16 version though'*

In [25]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

stemmer = PorterStemmer()
automotive['reviewText'] = automotive['reviewText'].apply(lambda x: ' '.join([stemmer.stem(y) for y in x.split()]))
#print(automotive['reviewText'].head(3))

0    need set jumper cabl new car good review good ...
1    long cabl work fine truck qualiti seem littl s...
2    cant comment much use come back updat review f...
Name: reviewText, dtype: object


5. Finally, filter the data by selecting reviews where the field <span style="background-color: #ccfff2">overall</span> is 4 or 5, and store the review texts in file <span style="background-color: #ccfff2">pos.txt</span>. Similarly, select reviews with rating 1 or 2 and store the reviews in file <span style="background-color: #ccfff2">neg.txt</span>. Ignore the reviews with overall rating 3. Each line in the two files should contain exactly one preprocessed review text without the rating.

In [36]:
pos, neg = (automotive.loc[automotive['overall']>=4])['reviewText'], (automotive.loc[automotive['overall']<=2])['reviewText']
np.savetxt(r'./pos.txt', pos.values, fmt='%s')
np.savetxt(r'./neg.txt', neg.values, fmt='%s')

Having created two collections of positive and negative reviews, respectively, you may wish to take a quick look to see how the review texts differ between them (positive vs negative). We will be using this data later to experiment with machine learning methods.

**Remember to submit your code on Moodle. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences. No need to submit the text files.**